"""Initial schema

Revision ID: 964964e09fd5
Revises: 
Create Date: 2026-03-07 07:28:33.328998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '964964e09fd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('content_draft', sa.Text(), nullable=True),
    sa.Column('content_final', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('outline', sa.Text(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=50), nullable=True),
    sa.Column('ai_generation_cost', sa.Float(), nullable=False),
    sa.Column('ai_tokens_used', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('fact_check_report', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('fact_check_passed', sa.Boolean(), nullable=True),
    sa.Column('fact_check_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fact_check_issues', sa.Integer(), nullable=False),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('seo_analysis', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_title', sa.String(length=70), nullable=True),
    sa.Column('meta_description', sa.String(length=170), nullable=True),
    sa.Column('keyword_density', sa.Float(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('plagiarism_percent', sa.Float(), nullable=True),
    sa.Column('original_content_percent', sa.Float(), nullable=True),
    sa.Column('eeat_experience', sa.Integer(), nullable=True),
    sa.Column('eeat_expertise', sa.Integer(), nullable=True),
    sa.Column('eeat_authoritativeness', sa.Integer(), nullable=True),
    sa.Column('eeat_trustworthiness', sa.Integer(), nullable=True),
    sa.Column('wordpress_post_id', sa.Integer(), nullable=True),
    sa.Column('wordpress_url', sa.String(length=500), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('internal_links', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('external_links', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('featured_image_id', sa.Integer(), nullable=True),
    sa.Column('featured_image_url', sa.String(length=500), nullable=True),
    sa.Column('views_30_days', sa.Integer(), nullable=False),
    sa.Column('avg_time_on_page', sa.Float(), nullable=True),
    sa.Column('bounce_rate', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_articles_keyword'), 'articles', ['keyword'], unique=False)
    op.create_index('ix_articles_keyword_status', 'articles', ['keyword', 'status'], unique=False)
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.create_index('ix_articles_status_created', 'articles', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_articles_wordpress_post_id'), 'articles', ['wordpress_post_id'], unique=False)
    op.create_table('article_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.Column('avg_time_on_page', sa.Float(), nullable=True),
    sa.Column('bounce_rate', sa.Float(), nullable=True),
    sa.Column('scroll_depth', sa.Float(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('avg_position', sa.Float(), nullable=True),
    sa.Column('top_queries', sa.JSON(), nullable=True),
    sa.Column('ad_revenue', sa.Float(), nullable=True),
    sa.Column('affiliate_revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_metrics_article_id'), 'article_metrics', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_metrics_date'), 'article_metrics', ['date'], unique=False)
    op.create_index('ix_metrics_article_date', 'article_metrics', ['article_id', 'date'], unique=True)
    op.create_table('article_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True),
    sa.Column('reviewer_name', sa.String(length=100), nullable=True),
    sa.Column('content_quality', sa.Integer(), nullable=True),
    sa.Column('originality', sa.Integer(), nullable=True),
    sa.Column('eeat_compliance', sa.Integer(), nullable=True),
    sa.Column('seo_quality', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('issues_found', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('revision_notes', sa.Text(), nullable=True),
    sa.Column('sections_to_revise', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('review_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_hours', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_reviews_article_id'), 'article_reviews', ['article_id'], unique=False)
    op.create_table('content_briefs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('brief_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('serp_features', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('competitor_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_briefs_keyword'), 'content_briefs', ['keyword'], unique=False)
    op.create_table('content_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('pub_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_writer', sa.String(length=100), nullable=True),
    sa.Column('assigned_reviewer', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_calendar_keyword'), 'content_calendar', ['keyword'], unique=False)
    op.create_index(op.f('ix_content_calendar_status'), 'content_calendar', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_calendar_status'), table_name='content_calendar')
    op.drop_index(op.f('ix_content_calendar_keyword'), table_name='content_calendar')
    op.drop_table('content_calendar')
    op.drop_index(op.f('ix_content_briefs_keyword'), table_name='content_briefs')
    op.drop_table('content_briefs')
    op.drop_index(op.f('ix_article_reviews_article_id'), table_name='article_reviews')
    op.drop_table('article_reviews')
    op.drop_index('ix_metrics_article_date', table_name='article_metrics')
    op.drop_index(op.f('ix_article_metrics_date'), table_name='article_metrics')
    op.drop_index(op.f('ix_article_metrics_article_id'), table_name='article_metrics')
    op.drop_table('article_metrics')
    op.drop_index(op.f('ix_articles_wordpress_post_id'), table_name='articles')
    op.drop_index('ix_articles_status_created', table_name='articles')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_index('ix_articles_keyword_status', table_name='articles')
    op.drop_index(op.f('ix_articles_keyword'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
