#!/usr/bin/env python3
"""Add the layout columns used by the homepage/footer build (idempotent).

    articles.page_layout  TEXT    NOT NULL DEFAULT 'article'
    articles.home_slot    TEXT    NOT NULL DEFAULT 'auto'
    articles.home_weight  INTEGER NOT NULL DEFAULT 0

Every existing and future row gets a default, so a page generated by the pipeline
renders correctly with no manual frontmatter. Backfill: rows flagged
`featured=true` become `home_slot='hero'` so the homepage hero survives the
switch from the boolean to the slot attribute.
"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from dotenv import load_dotenv  # noqa: E402

load_dotenv(Path(__file__).resolve().parents[1] / ".env")

from sqlalchemy import create_engine, text  # noqa: E402


def main() -> None:
    engine = create_engine(os.environ["DATABASE_URL"])
    stmts = [
        "ALTER TABLE articles ADD COLUMN IF NOT EXISTS page_layout VARCHAR(32) NOT NULL DEFAULT 'article'",
        "ALTER TABLE articles ADD COLUMN IF NOT EXISTS home_slot VARCHAR(16) NOT NULL DEFAULT 'auto'",
        "ALTER TABLE articles ADD COLUMN IF NOT EXISTS home_weight INTEGER NOT NULL DEFAULT 0",
        # backfill: the old featured boolean becomes an explicit hero slot
        "UPDATE articles SET home_slot='hero' WHERE featured IS TRUE AND home_slot='auto'",
    ]
    with engine.begin() as c:
        for s in stmts:
            c.execute(text(s))
            print("✅", s[:78])
        rows = c.execute(
            text("select home_slot, count(*) from articles group by home_slot order by 2 desc")
        ).fetchall()
        print("\nrows by home_slot:", rows)
        print("rows by page_layout:", c.execute(
            text("select page_layout, count(*) from articles group by page_layout")
        ).fetchall())


if __name__ == "__main__":
    main()
