#!/usr/bin/env python3
import re
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from blog_automation.models import Article, get_session
from blog_automation.pipelines.phase_8_publish.publishing import format_markdown_to_html

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <meta name="description" content="{meta_description}">
    <style>
        :root {{
            --primary: #2563eb;
            --text: #1f2937;
            --bg: #ffffff;
            --muted: #6b7280;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
                Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: var(--text);
            background: #f9fafb;
            margin: 0;
            padding: 0;
        }}
        .container {{
            max-width: 800px;
            margin: 40px auto;
            padding: 40px;
            background: var(--bg);
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }}
        header {{
            margin-bottom: 40px;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 20px;
        }}
        h1 {{
            font-size: 2.5rem;
            margin-bottom: 10px;
            line-height: 1.2;
        }}
        .meta {{
            color: var(--muted);
            font-size: 0.9rem;
        }}
        .content {{
            font-size: 1.125rem;
        }}
        .content h2 {{
            margin-top: 2rem;
            color: #111827;
        }}
        .content img {{
            max-width: 100%;
            height: auto;
            border-radius: 4px;
        }}
        footer {{
            margin-top: 60px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: var(--muted);
            font-size: 0.875rem;
        }}
        .badge {{
            display: inline-block;
            padding: 0.25rem 0.75rem;
            border-radius: 9999px;
            font-size: 0.75rem;
            font-weight: 600;
            background: #dbeafe;
            color: #1e40af;
            margin-bottom: 1rem;
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <div class="badge">AI-Generated & Fact-Checked</div>
            <h1>{title}</h1>
            <div class="meta">
                Published on {date} • {word_count} words • Topic: {keyword}
            </div>
        </header>
        <div class="content">
            {content_html}
        </div>
        <footer>
            <p>&copy; 2024 AI Blog Automation Platform. All rights reserved.</p>
            <p>Generated by {ai_model} • SEO Score: {seo_score}/100</p>
        </footer>
    </div>
</body>
</html>
"""


def export_article(article_id: int, output_dir: str = "dist"):
    with get_session() as session:
        article = session.query(Article).get(article_id)
        if not article:
            print(f"❌ Article {article_id} not found")
            return

        print(f"📦 Exporting article: {article.title}")

        # Ensure output directory exists
        Path(output_dir).mkdir(parents=True, exist_ok=True)

        content = article.content_final or article.content_draft or ""
        html_body = format_markdown_to_html(content)

        # Remove Gutenberg comments for static HTML
        html_body = re.sub(r"<!-- /?wp:.*? -->", "", html_body)

        full_html = HTML_TEMPLATE.format(
            title=article.title,
            meta_description=article.meta_description or "",
            date=article.created_at.strftime("%B %d, %Y"),
            word_count=article.word_count or 0,
            keyword=article.keyword,
            content_html=html_body,
            ai_model=article.ai_model_used or "GPT-4",
            seo_score=article.seo_score or 0,
        )

        file_path = Path(output_dir) / f"{article.slug}.html"
        with open(file_path, "w") as f:
            f.write(full_html)

        print(f"✅ Successfully exported to: {file_path}")
        return file_path


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python export_static.py <article_id>")
        sys.exit(1)

    export_article(int(sys.argv[1]))
