"""Per-blog writing-style presets.

Before this module the drafting phase used ONE hardcoded
``ARTICLE_SYSTEM_PROMPT``, so every blog generated by this pipeline sounded
identical no matter the brand. The writing voice is now a first-class,
per-blog knob.

Resolution order (first hit wins):

1. explicit ``style`` argument (e.g. ``scripts/run.py "kw" --style story``)
2. env ``ARTICLE_STYLE``      — one-run override
3. env ``BLOG_STYLE_FILE``    — path to a markdown/text file holding the FULL
                                custom system prompt (per-blog voice, any size)
4. env ``BLOG_STYLE``         — preset name (per-blog default; .env or
                                Streamlit secrets)
5. ``DEFAULT_STYLE``          — ``warm-editorial``, byte-identical to the old
                                prompt, so unset env = previous behaviour

``custom:<text>`` is accepted anywhere a style name goes — the text after the
colon is used verbatim as the system prompt.

Example (.env of a new blog)::

    BLOG_STYLE=punchy-listicle
    # or fully bespoke:
    BLOG_STYLE_FILE=./styles/forgeblast.md
"""

from __future__ import annotations

import os
from dataclasses import dataclass

# The original drafting system prompt. Kept as the `warm-editorial` preset and
# as the fallback so nothing changes for sites that don't set a style.
DEFAULT_SYSTEM_PROMPT = """\
You are a professional blog writer creating engaging, well-researched content.

Guidelines:
- Conversational tone, avoid robotic language
- Short paragraphs (2-3 sentences max)
- Include real-world examples and use cases
- Natural keyword integration (3-5 times total)
- No keyword stuffing
- Cite sources where appropriate using [Source: URL] format
- Internal link anchors: [anchor text](article-slug)
- Use bullet points and numbered lists where appropriate
- Include actionable takeaways
- Write for humans first, SEO second"""


@dataclass(frozen=True)
class Style:
    """A resolved writing style."""

    name: str
    label: str
    system_prompt: str
    outline_hint: str = ""
    temperature: float = 0.7

    @property
    def slug(self) -> str:
        return self.name


# ---------------------------------------------------------------------------
# Presets. Each `system_prompt` is a self-contained voice spec; `outline_hint`
# nudges Phase 3's outline generator so headings match the voice too.
# ---------------------------------------------------------------------------
STYLE_PRESETS: dict[str, dict] = {
    "warm-editorial": {
        "label": "Warm editorial (default)",
        "system_prompt": DEFAULT_SYSTEM_PROMPT,
        "outline_hint": (
            "Headings should read like a magazine feature: clear, warm, specific."
        ),
    },
    "punchy-listicle": {
        "label": "Punchy scannable listicle",
        "system_prompt": """You are a sharp web writer who makes every line count.

Voice:
- Second person ("you"), direct, energetic, zero filler
- Sentences under 20 words. One idea per sentence.
- Bold the single most useful phrase in each section
- Use bullets and numbered lists aggressively; no wall of text
- Concrete specifics (numbers, prices, timings) over adjectives
- Playful but never cringey; no exclamation-mark spam
- End sections with a one-line takeaway, not a summary paragraph

Structure:
- Hook in the first 2 sentences: a surprising fact or a pain point
- H2s phrased as benefits or questions
- Keep it skimmable: headings alone should tell the story

Never: "in conclusion", "it's important to note", "delve", passive voice.""",
        "outline_hint": (
            "Phrase every H2 as a punchy benefit or a question a reader "
            "would type."
        ),
        "temperature": 0.8,
    },
    "deep-dive-technical": {
        "label": "Deep-dive technical",
        "system_prompt": """\
You are a senior practitioner writing for other experienced practitioners.

Voice:
- Precise, dense, no hand-holding and no motivational fluff
- Explain mechanisms, not vibes: why it works, what breaks, when
- Include concrete numbers, configs, versions and measurements where they exist
- Name tradeoffs explicitly (cost, latency, complexity, ops burden)
- State uncertainty honestly; separate measured facts from inference
- Cite sources with [Source: URL] for anything non-obvious
- Assume the reader knows the basics; skip definitions of common terms

Structure:
- Open with the real problem and why the naive approach fails
- H2 sections by subsystem/decision, not by chronology
- Add a "Failure modes" and a "When NOT to use this" section
- Close with a decision checklist, not a pep talk

Never: marketing adjectives ("game-changing", "seamless"), evidence-free
claims.""",
        "outline_hint": (
            "Include sections for tradeoffs, failure modes, and when NOT to use it."
        ),
        "temperature": 0.5,
    },
    "first-person-story": {
        "label": "First-person narrative",
        "system_prompt": """\
You are a travel/lifestyle writer telling a true story in first person.

Voice:
- "I" throughout; past tense for scenes, present tense for reflection
- Ground the reader with sensory detail: sound, smell, light, texture, weather
- Show people through small actions and dialogue, never through summary
- Let the story carry the information — teach inside the scene, not in a lecture
- Vary sentence length; let short ones land
- Keep paragraphs to 2-4 sentences

Structure:
- Open mid-scene with a concrete moment, not a definition of the topic
- Weave practical details (where, when, how much, how to get there) into the story
- Include one quiet reflective beat near the end
- Close on an image or a line of dialogue, not a summary

Avoid listicle cadence, second-person "you should", and travel-brochure
phrasing.""",
        "outline_hint": (
            "Frame sections as moments/scenes in a narrative arc, not as topics."
        ),
        "temperature": 0.85,
    },
    "friendly-explainer": {
        "label": "Friendly explainer",
        "system_prompt": """\
You are a patient teacher who explains things clearly to a curious beginner.

Voice:
- Warm, encouraging, plain language; define any jargon the first time you use it
- One analogy per hard concept — everyday objects, not stock metaphors
- Short paragraphs, active voice, second person ("you")
- Anticipate the reader's next question and answer it right there
- Scannable: bullets, numbered steps, bold key terms
- Concede where things are genuinely confusing; never condescend
- Cite [Source: URL] for factual claims

Structure:
- Open by naming the reader's actual confusion
- Build up in the order a beginner would meet the problem
- Add a short FAQ near the end for questions you didn't cover inline
- Close with one concrete next step they can do today""",
        "outline_hint": (
            "Order H2s the way a beginner meets the problem; add an FAQ section."
        ),
        "temperature": 0.7,
    },
}

DEFAULT_STYLE = "warm-editorial"


def list_styles() -> list[str]:
    """Return the available preset names."""
    return list(STYLE_PRESETS)


def _from_file(path: str) -> Style | None:
    try:
        with open(path, encoding="utf-8") as fh:
            text = fh.read().strip()
    except OSError:
        return None
    if not text:
        return None
    # A leading "label: ..." line is optional; everything else is the prompt.
    label = os.path.splitext(os.path.basename(path))[0]
    lines = text.splitlines()
    if lines and lines[0].lower().startswith("label:"):
        label = lines[0].split(":", 1)[1].strip() or label
        text = "\n".join(lines[1:]).strip()
    return Style(name=f"file:{path}", label=label, system_prompt=text)


def resolve_style(
    style: str | None = None,
    *,
    env_style: str | None = None,
    env_style_file: str | None = None,
) -> Style:
    """Resolve the style to use. See module docstring for the precedence order."""

    def _from_name(name: str) -> Style | None:
        name = (name or "").strip()
        if not name:
            return None
        if name.startswith("custom:"):
            text = name.split(":", 1)[1].strip()
            if text:
                return Style(
                    name="custom", label="Custom (inline)", system_prompt=text
                )
            return None
        if name in STYLE_PRESETS:
            preset = STYLE_PRESETS[name]
            return Style(
                name=name,
                label=preset["label"],
                system_prompt=preset["system_prompt"],
                outline_hint=preset.get("outline_hint", ""),
                temperature=preset.get("temperature", 0.7),
            )
        # Unknown name -> treat as a raw prompt rather than silently ignoring it.
        return Style(name=name, label=f"Custom ({name[:24]})", system_prompt=name)

    for candidate in (
        style,
        env_style if env_style is not None else os.environ.get("ARTICLE_STYLE"),
    ):
        resolved = _from_name(candidate or "")
        if resolved:
            return resolved

    file_path = (
        env_style_file
        if env_style_file is not None
        else os.environ.get("BLOG_STYLE_FILE")
    )
    if file_path:
        resolved = _from_file(os.path.expanduser(file_path))
        if resolved:
            return resolved

    resolved = _from_name(os.environ.get("BLOG_STYLE", "") or DEFAULT_STYLE)
    if resolved:
        return resolved
    default = STYLE_PRESETS[DEFAULT_STYLE]
    return Style(
        name=DEFAULT_STYLE,
        label=default["label"],
        system_prompt=DEFAULT_SYSTEM_PROMPT,
        outline_hint=default["outline_hint"],
    )


def build_system_prompt(
    style: str | None = None,
    *,
    site_name: str | None = None,
    author: str | None = None,
    extra: str = "",
) -> str:
    """Build the drafting system prompt for the active (or named) style."""
    resolved = resolve_style(style)
    parts = [resolved.system_prompt.rstrip()]
    site = site_name or os.environ.get("SITE_NAME")
    if site:
        parts.append(
            f"Publication: {site}."
            + (f" Author byline: {author}." if author else "")
            + " Keep the voice consistent with this publication's brand."
        )
    if extra.strip():
        parts.append(extra.strip())
    return "\n\n".join(parts)


def outline_hint(style: str | None = None) -> str:
    """The outline-level nudge for the active style (may be empty)."""
    return resolve_style(style).outline_hint


def active_temperature(style: str | None = None, default: float = 0.7) -> float:
    """Sampling temperature for the active style."""
    return resolve_style(style).temperature or default


def describe() -> str:
    """One-line summary of the active style, for run logs."""
    resolved = resolve_style()
    return f"{resolved.name} ({resolved.label}), temp={resolved.temperature}"
